config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root to: "home#index"

  get 'terms' => 'terms#index'
  get 'about' => 'about#index'
  resources :articles do
    resources :comments
  end
  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resource :comments, only: [:create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence: true, :length => maximum(140)
    validates :text, presence: true, :length => maximum(4000)

    def subject
        title
    end
    def last_comment
        comments.last
    end
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :body, presence: true, :length => maximum(4000)
  
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates :email, presence: true
    validates :message, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :authenticate_user!, :only => [:new, :create]

def index 
    @articles = Article.all
end

def show
    @article = Article.find(params[:id])
end

def new
end

def create
    @article = Article.new(article_params)
    if @article.valid? 
        @article.save
        redirect_to @article
    else
        render action: 'new'
    end
end

def edit
    @article = Article.find(params[:id])
end

def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
        redirect_to @article
    else
        render action: 'edit'
    end
end

def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
end

private
    def article_params
        params.require(:article).permit(:title, :text)
    end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!, :only => [:new, :create]

def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
end

def show
    @comments = Comment.all
end

private 
def comment_params
    params.require(:comment).permit(:author, :body)
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   
    def new
    end

    def create 
        @contact = Contact.new(contact_params)
        
        if @contact.valid?
            @contact.save
        else
            render action: 'new'
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:email, :message)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController

def index
end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/about/index.html.erb
<h1>About</h1>
<p>Lets talk about it</p>

app/views/articles/create.html.erb
<h1>article successfully created</h1>
<a href="articles_path">Show articles</a><br />
<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <p><%= f.label :title %><br/>
  <%= f.text_field :title %></p>

  <p><%= f.label :text %><br/>
  <%= f.text_area :text %></p>

  <p><%= f.submit %></p>
  
<% end %>

<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure"} %>

app/views/articles/index.html.erb
<h1>List of articles</h1>

<% @articles.each do |article| %>
    <h3><%= article.title %></h3>
    <p><%= article.text %></p>
    <%= link_to "Show article", article_path(article) %>
    <%= link_to "Edit article", edit_article_path(article) %>
    
    <hr />
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p><%= f.label :title %><br/>
  <%= f.text_field :title %></p>

  <p><%= f.label :text %><br/>
  <%= f.text_area :text %></p>

  <p><%= f.submit %></p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.text %></p>

<h2>Add Comment</h2>
<%= form_for([@article, @article.comments.build])  do |f| %>
    
    <p><%= f.label :body %><br/>
    <%= f.text_area :body %></p>

    <p><%= f.submit %></p>

<% end %>
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
    <i><%= current_user.username %> said:</i>
    
    <i><%= comment.body %></i>
    <hr />
<% end %>

app/views/contacts/create.html.erb
<h1>Thanks!</h1>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us')%></h1>

<%= form_for :contact, url: contacts_path do |f| %>
  
  <%if @contact && @contact.errors.any? %>
  <p>
    <ul>
    <%= @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <%end%>
    </ul>
  </p>
  <% end %>

  <p><%= f.label :email %><br/>
  <%= f.text_field :email %></p>

  <p><%= f.label :message %><br/>
  <%= f.text_area :message %></p>

  <p><%= f.submit 'Send message' %></p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <!--/-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href=<%= home_index_url %>>My Blog</a>
       
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href=<%= home_index_url %>>Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=<%= articles_url %>>Articles</a>
            </li>
            <li class="nav-item">            
              <a class="nav-link btn btn-outline-primary" href=<%= new_article_url %>>New Article</a>
            </li>            
          </ul>
          <div class="nav-item d-flex">
            <% if user_signed_in? %>
                    <p>Hello, <%= current_user.username %>   |  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
            <% else%>
              <%= link_to 'Log In', new_user_session_path%> 
            <% end %>
          </div>
          
        </div>
      </div>
    </nav>

      <br />     

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>   


    </div> <!-- /.container -->
  </body>
</html>

app/views/terms/index.html.erb
<h1>Terms of service</h1>
<p>Constant agreement that customer owns us a lot of money.</p>